### PR TITLE
Add php7 support and image resolution for templates

### PR DESCRIPTION
**Pull request by rubo77**
This will give you the option to add image-width and image-height to your templates, for example:

    <a itemprop="contentUrl" data-size="{file:width}x{file:height}" href="{file:link}">{file:thumbnail}</a>

### CODE REVIEW

**Comment by dclaybrook** [comment]
There's still a problem when caching is used enabled with PHP7 (after applying the magic_quotes fix). Any chance this can get some attention as well for "full" php7 support?

`Error: Call to a member function __toString() on boolean in /var/www/html/index.php:637 Stack trace: #0 {main}`

**Comment by rubo77** [comment]
Maybe just comment or that 2 lines.

**Comment by dclaybrook** [comment]
That was the first thing I tried :)

**Comment by rubo77** [comment]
If you find a workaround, please report it here

**Pull request closed without merging**
